### ISSUE TITLE
Troubles running example of CQELS

### ISSUE THREAD

**Issue by abdelkader4004** [cqels/LGPL#4]
Hello,
I am trying to run a stream processing pipeline based on CQELS in part of my project.
I met some bugs in this pipeline. It seems that TripleWave is crashing after sending a couple of stream elements through the WebSocket.
I wonder if there exist stable execution environments for this pipeline. And which versions of libraries I must use.
Here attached my config and stream.rs files: [stream.zip](https://github.com/cqels/CQELS-1.x/files/10335929/stream.zip) , [config.zip](https://github.com/cqels/CQELS-1.x/files/10335932/config.zip).

**Comment by anhlt18vn** [comment]
Hi, 

I am not the author of triplewave. But if you upload the crashing log of triplewave here. I can have a look if I can help.

Best,
Anh.

**Comment by abdelkader4004** [comment]
In fact, I want to run basic example of CQELS, for example CQELSServerExample.java and CQELSClientExample.java.
I want to know how this example is built, and what I need to run it.

**Comment by anhlt18vn** [comment]
First, you need a stream player to send data via WebSocket. In the example, I used the simple TripleWave tool for data streaming. Next, start the example server, and then register a query with the server, as shown in the client example.

**Comment by abdelkader4004** [comment]
It seems to need updating dependencies. I'm getting this error when running CQELSServerExample,

Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/AttributeContainerMap
	at org.eclipse.jetty.server.Server.<init>(Server.java:79)
	at org.eclipse.jetty.server.Server.<init>(Server.java:106)
	at org.deri.cqels.integration.websocket.WebsocketCQELSServer.start(WebsocketCQELSServer.java:72)
	at org.deri.cqels.example.CQELSServerExample.main(CQELSServerExample.java:22)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.component.AttributeContainerMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more

**Comment by anhlt18vn** [comment]
Could you let me know how you executed the code? You should be able to build a fat JAR with this POM file. You don't have to update the dependencies.
